### ISSUE TITLE
Undefined Property Warning

### ISSUE THREAD

**Issue by boone** [bugguide/issues#8]
https://beta.bugguide.net/node/129337/bgpage

<img width="815" alt="Screen Shot 2021-06-04 at 7 13 48 PM" src="https://user-images.githubusercontent.com/6807/120871201-00c3c500-c569-11eb-943f-0b6db3904a5b.png">

**Comment by clouseau** [comment]
Ah, an intuitive error! Ha ha.

Background: BugGuide 2.0 indexes all bgimages into Apache Solr for speed of retrieval. During the migration process the database is imported and then it walks through and indexes all the things.

When the $ss\_bgimage\_thumbnail is undefined it means that BugGuide correctly retrieved the entity id from the Apache Solr index; however, there was no image information along with it. I'd like to go one more migration and indexing cycle before we call this a bug.

Reference: bugguide internal issue #160.

**Comment by clouseau** [comment]
The notices appear to be gone now that the next migration and index are complete.
